sudo: required

services:
  - docker

env:
  - DOVECOT=release-2.2.21 
  - DOVECOT=master-2.3 
  - DOVECOT=master-2.2 
  
script:
  - docker build --build-arg DOVECOT=$DOVECOT -t travis-build build
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker tag travis-build cephdovecot/travis-build:$DOVECOT
  - docker push cephdovecot/travis-build:$DOVECOT;
