sudo: required

services:
  - docker

env:
  - DOVECOT=release-2.2.21 IMAPTEST=bb98e05dea6e1b44033c38e2681c7acb7e076073
  - DOVECOT=2.2.33.1 IMAPTEST=core-2.2
  - DOVECOT=master IMAPTEST=master
  - DOVECOT=master-2.2 IMAPTEST=core-2.2
  
script:
  - docker build --build-arg DOVECOT=$DOVECOT --build-arg IMAPTEST=$IMAPTEST -t travis-build build
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker tag travis-build cephdovecot/travis-build:$DOVECOT
  - docker push cephdovecot/travis-build:$DOVECOT;
