sudo: required

services:
  - docker

env:
  DOVECOT=release-2.2.21
  DOVECOT=release-2.2.32

script:
  - docker build -t travis-build build
  - docker tag travis-build cephdovecot/travis-build:$DOVECOT
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push cephdovecot/travis-build:$DOVECOT;
    fi